//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/std_msgs"
)

type SysStatus struct {
	msg.Package      `ros:"mavros_msgs"`
	Header           std_msgs.Header
	SensorsPresent   uint32
	SensorsEnabled   uint32
	SensorsHealth    uint32
	Load             uint16
	VoltageBattery   uint16
	CurrentBattery   int16
	BatteryRemaining int8
	DropRateComm     uint16
	ErrorsComm       uint16
	ErrorsCount1     uint16
	ErrorsCount2     uint16
	ErrorsCount3     uint16
	ErrorsCount4     uint16
}
