//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/std_msgs"
)

type ESCStatusItem struct {
	msg.Package `ros:"mavros_msgs"`
	Header      std_msgs.Header
	Rpm         int32
	Voltage     float32
	Current     float32
}
