//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/std_msgs"
)

type HilActuatorControls struct {
	msg.Package `ros:"mavros_msgs"`
	Header      std_msgs.Header
	Controls    [16]float32
	Mode        uint8
	Flags       uint64
}
