//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type CellularStatus struct {
	msg.Package   `ros:"mavros_msgs"`
	Status        uint8
	FailureReason uint8
	Type          uint8
	Quality       uint8
	Mcc           uint16
	Mnc           uint16
	Lac           uint16
}
