//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/geographic_msgs"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/geometry_msgs"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/std_msgs"
)

type HomePosition struct {
	msg.Package `ros:"mavros_msgs"`
	Header      std_msgs.Header
	Geo         geographic_msgs.GeoPoint
	Position    geometry_msgs.Point
	Orientation geometry_msgs.Quaternion
	Approach    geometry_msgs.Vector3
}
