//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/aler9/goroslib/pkg/msg"
	"github.com/aler9/goroslib/pkg/msgs/std_msgs"
)

type TerrainReport struct {
	msg.Package   `ros:"mavros_msgs"`
	Header        std_msgs.Header
	Latitude      float64
	Longitude     float64
	Spacing       uint16
	TerrainHeight float32
	CurrentHeight float32
	Pending       uint16
	Loaded        uint16
}
