//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type WaypointList struct {
	msg.Package `ros:"mavros_msgs"`
	CurrentSeq  uint16
	Waypoints   []Waypoint
}
