//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/aler9/goroslib/pkg/msg"
)

const (
	Waypoint_FRAME_GLOBAL                  uint8 = 0
	Waypoint_FRAME_LOCAL_NED               uint8 = 1
	Waypoint_FRAME_MISSION                 uint8 = 2
	Waypoint_FRAME_GLOBAL_REL_ALT          uint8 = 3
	Waypoint_FRAME_LOCAL_ENU               uint8 = 4
	Waypoint_FRAME_GLOBAL_INT              uint8 = 5
	Waypoint_FRAME_GLOBAL_RELATIVE_ALT_INT uint8 = 6
	Waypoint_FRAME_LOCAL_OFFSET_NED        uint8 = 7
	Waypoint_FRAME_BODY_NED                uint8 = 8
	Waypoint_FRAME_BODY_OFFSET_NED         uint8 = 9
	Waypoint_FRAME_GLOBAL_TERRAIN_ALT      uint8 = 10
	Waypoint_FRAME_GLOBAL_TERRAIN_ALT_INT  uint8 = 11
	Waypoint_FRAME_BODY_FRD                uint8 = 12
	Waypoint_FRAME_RESERVED_13             uint8 = 13
	Waypoint_FRAME_RESERVED_14             uint8 = 14
	Waypoint_FRAME_RESERVED_15             uint8 = 15
	Waypoint_FRAME_RESERVED_16             uint8 = 16
	Waypoint_FRAME_RESERVED_17             uint8 = 17
	Waypoint_FRAME_RESERVED_18             uint8 = 18
	Waypoint_FRAME_RESERVED_19             uint8 = 19
	Waypoint_FRAME_LOCAL_FRD               uint8 = 20
	Waypoint_FRAME_LOCAL_FLU               uint8 = 21
)

type Waypoint struct {
	msg.Package     `ros:"mavros_msgs"`
	msg.Definitions `ros:"uint8 FRAME_GLOBAL=0,uint8 FRAME_LOCAL_NED=1,uint8 FRAME_MISSION=2,uint8 FRAME_GLOBAL_REL_ALT=3,uint8 FRAME_LOCAL_ENU=4,uint8 FRAME_GLOBAL_INT=5,uint8 FRAME_GLOBAL_RELATIVE_ALT_INT=6,uint8 FRAME_LOCAL_OFFSET_NED=7,uint8 FRAME_BODY_NED=8,uint8 FRAME_BODY_OFFSET_NED=9,uint8 FRAME_GLOBAL_TERRAIN_ALT=10,uint8 FRAME_GLOBAL_TERRAIN_ALT_INT=11,uint8 FRAME_BODY_FRD=12,uint8 FRAME_RESERVED_13=13,uint8 FRAME_RESERVED_14=14,uint8 FRAME_RESERVED_15=15,uint8 FRAME_RESERVED_16=16,uint8 FRAME_RESERVED_17=17,uint8 FRAME_RESERVED_18=18,uint8 FRAME_RESERVED_19=19,uint8 FRAME_LOCAL_FRD=20,uint8 FRAME_LOCAL_FLU=21"`
	Frame           uint8
	Command         uint16
	IsCurrent       bool
	Autocontinue    bool
	Param1          float32
	Param2          float32
	Param3          float32
	Param4          float32
	XLat            float64
	YLong           float64
	ZAlt            float64
}
