//autogenerated:yes
//nolint:revive,lll
package mavros_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type CommandLongReq struct {
	msg.Package  `ros:"mavros_msgs"`
	Broadcast    bool
	Command      uint16
	Confirmation uint8
	Param1       float32
	Param2       float32
	Param3       float32
	Param4       float32
	Param5       float32
	Param6       float32
	Param7       float32
}

type CommandLongRes struct {
	msg.Package `ros:"mavros_msgs"`
	Success     bool
	Result      uint8
}

type CommandLong struct {
	msg.Package `ros:"mavros_msgs"`
	CommandLongReq
	CommandLongRes
}
