// Package msgs contains the autogenerated standard messages.
package msgs

// Package is the type of an extra field that can be added to messages to set package name
type Package int

// Definitions is the type of an extra field that can be added to messages to add definitions
type Definitions int
