// Autogenerated with msg-import, do not edit.
package actionlib_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type GoalStatus struct {
	msgs.Package `ros:"actionlib_msgs"`
	GoalId       GoalID
	Status       uint8
	Text         string
}
