// Autogenerated with msg-import, do not edit.
package actionlib_msgs

import (
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type GoalStatusArray struct {
	Header     std_msgs.Header
	StatusList []GoalStatus
}
