// Autogenerated with msg-import, do not edit.
package actionlib_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type GoalID struct {
	msgs.Package `ros:"actionlib_msgs"`
	Stamp        msgs.Time
	Id           msgs.String
}
