//autogenerated:yes
//nolint:revive,lll
package std_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type ColorRGBA struct {
	msg.Package `ros:"std_msgs"`
	R           float32
	G           float32
	B           float32
	A           float32
}
