//autogenerated:yes
//nolint:revive,lll
package std_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type UInt8MultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []uint8
}
