//autogenerated:yes
//nolint:revive,lll
package std_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type Byte struct {
	msg.Package `ros:"std_msgs"`
	Data        int8 `rostype:"byte"`
}
