// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type BatteryState struct {
	msgs.Package          `ros:"sensor_msgs"`
	Header                std_msgs.Header
	Voltage               float32
	Temperature           float32
	Current               float32
	Charge                float32
	Capacity              float32
	DesignCapacity        float32
	Percentage            float32
	PowerSupplyStatus     uint8
	PowerSupplyHealth     uint8
	PowerSupplyTechnology uint8
	Present               bool
	CellVoltage           []float32
	CellTemperature       []float32
	Location              string
	SerialNumber          string
}
