// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type BatteryState struct {
	Header                std_msgs.Header
	Voltage               msgs.Float32
	Temperature           msgs.Float32
	Current               msgs.Float32
	Charge                msgs.Float32
	Capacity              msgs.Float32
	DesignCapacity        msgs.Float32
	Percentage            msgs.Float32
	PowerSupplyStatus     msgs.Uint8
	PowerSupplyHealth     msgs.Uint8
	PowerSupplyTechnology msgs.Uint8
	Present               msgs.Bool
	CellVoltage           []msgs.Float32
	CellTemperature       []msgs.Float32
	Location              msgs.String
	SerialNumber          msgs.String
}
