// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msg"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type Illuminance struct {
	Header      std_msgs.Header
	Illuminance msg.Float64
	Variance    msg.Float64
}
