// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type Illuminance struct {
	Header      std_msgs.Header
	Illuminance msgs.Float64
	Variance    msgs.Float64
}
