// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type Image struct {
	Header      std_msgs.Header
	Height      msgs.Uint32
	Width       msgs.Uint32
	Encoding    msgs.String
	IsBigendian msgs.Uint8
	Step        msgs.Uint32
	Data        []msgs.Uint8
}
