// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msg"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type JointState struct {
	Header   std_msgs.Header
	Name     []msg.String
	Position []msg.Float64
	Velocity []msg.Float64
	Effort   []msg.Float64
}
