// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type JointState struct {
	msgs.Package `ros:"sensor_msgs"`
	Header       std_msgs.Header
	Name         []string
	Position     []float64
	Velocity     []float64
	Effort       []float64
}
