// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type JointState struct {
	Header   std_msgs.Header
	Name     []msgs.String
	Position []msgs.Float64
	Velocity []msgs.Float64
	Effort   []msgs.Float64
}
