// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msg"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type Joy struct {
	Header  std_msgs.Header
	Axes    []msg.Float32
	Buttons []msg.Int32
}
