// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msg"
)

type JoyFeedback struct {
	Type      msg.Uint8
	Id        msg.Uint8
	Intensity msg.Float32
}
