// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type JoyFeedback struct {
	Type      msgs.Uint8
	Id        msgs.Uint8
	Intensity msgs.Float32
}
