// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type MultiEchoLaserScan struct {
	msgs.Package   `ros:"sensor_msgs"`
	Header         std_msgs.Header
	AngleMin       msgs.Float32
	AngleMax       msgs.Float32
	AngleIncrement msgs.Float32
	TimeIncrement  msgs.Float32
	ScanTime       msgs.Float32
	RangeMin       msgs.Float32
	RangeMax       msgs.Float32
	Ranges         []LaserEcho
	Intensities    []LaserEcho
}
