// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type NavSatFix struct {
	msgs.Package           `ros:"sensor_msgs"`
	Header                 std_msgs.Header
	Status                 NavSatStatus
	Latitude               msgs.Float64
	Longitude              msgs.Float64
	Altitude               msgs.Float64
	PositionCovariance     [9]msgs.Float64
	PositionCovarianceType msgs.Uint8
}
