// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msg"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type NavSatFix struct {
	Header                 std_msgs.Header
	Status                 NavSatStatus
	Latitude               msg.Float64
	Longitude              msg.Float64
	Altitude               msg.Float64
	PositionCovariance     [9]msg.Float64
	PositionCovarianceType msg.Uint8
}
