// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type PointField struct {
	msgs.Package `ros:"sensor_msgs"`
	Name         msgs.String
	Offset       msgs.Uint32
	Datatype     msgs.Uint8
	Count        msgs.Uint32
}
