// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type PointField struct {
	msgs.Package `ros:"sensor_msgs"`
	Name         string
	Offset       uint32
	Datatype     uint8
	Count        uint32
}
