// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type PointCloud2 struct {
	Header      std_msgs.Header
	Height      msgs.Uint32
	Width       msgs.Uint32
	Fields      []PointField
	IsBigendian msgs.Bool
	PointStep   msgs.Uint32
	RowStep     msgs.Uint32
	Data        []msgs.Uint8
	IsDense     msgs.Bool
}
