// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type Range struct {
	msgs.Package  `ros:"sensor_msgs"`
	Header        std_msgs.Header
	RadiationType uint8
	FieldOfView   float32
	MinRange      float32
	MaxRange      float32
	Range         float32
}
