// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type RegionOfInterest struct {
	msgs.Package `ros:"sensor_msgs"`
	XOffset      msgs.Uint32
	YOffset      msgs.Uint32
	Height       msgs.Uint32
	Width        msgs.Uint32
	DoRectify    msgs.Bool
}
