// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msg"
)

type RegionOfInterest struct {
	XOffset   msg.Uint32
	YOffset   msg.Uint32
	Height    msg.Uint32
	Width     msg.Uint32
	DoRectify msg.Bool
}
