// Autogenerated with msg-import, do not edit.
package sensor_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type TimeReference struct {
	Header  std_msgs.Header
	TimeRef msgs.Time
	Source  msgs.String
}
