// Autogenerated with msg-import, do not edit.
package visualization_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/geometry_msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type ImageMarker struct {
	Header        std_msgs.Header
	Ns            msgs.String
	Id            msgs.Int32
	Type          msgs.Int32
	Action        msgs.Int32
	Position      geometry_msgs.Point
	Scale         msgs.Float32
	OutlineColor  std_msgs.ColorRGBA
	Filled        msgs.Uint8
	FillColor     std_msgs.ColorRGBA
	Lifetime      msgs.Duration
	Points        []geometry_msgs.Point
	OutlineColors []std_msgs.ColorRGBA
}
