// Autogenerated with msg-import, do not edit.
package visualization_msgs

import (
	"github.com/aler9/goroslib/msg"
	"github.com/aler9/goroslib/msgs/geometry_msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type InteractiveMarker struct {
	Header      std_msgs.Header
	Pose        geometry_msgs.Pose
	Name        msg.String
	Description msg.String
	Scale       msg.Float32
	MenuEntries []MenuEntry
	Controls    []InteractiveMarkerControl
}
