// Autogenerated with msg-import, do not edit.
package visualization_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/geometry_msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type InteractiveMarkerFeedback struct {
	msgs.Package    `ros:"visualization_msgs"`
	Header          std_msgs.Header
	ClientId        string
	MarkerName      string
	ControlName     string
	EventType       uint8
	Pose            geometry_msgs.Pose
	MenuEntryId     uint32
	MousePoint      geometry_msgs.Point
	MousePointValid bool
}
