// Autogenerated with msg-import, do not edit.
package visualization_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/geometry_msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type InteractiveMarkerFeedback struct {
	Header          std_msgs.Header
	ClientId        msgs.String
	MarkerName      msgs.String
	ControlName     msgs.String
	EventType       msgs.Uint8
	Pose            geometry_msgs.Pose
	MenuEntryId     msgs.Uint32
	MousePoint      geometry_msgs.Point
	MousePointValid msgs.Bool
}
