// Autogenerated with msg-import, do not edit.
package visualization_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type InteractiveMarkerUpdate struct {
	ServerId msgs.String
	SeqNum   msgs.Uint64
	Type     msgs.Uint8
	Markers  []InteractiveMarker
	Poses    []InteractiveMarkerPose
	Erases   []msgs.String
}
