// Autogenerated with msg-import, do not edit.
package visualization_msgs

import (
	"github.com/aler9/goroslib/msg"
)

type InteractiveMarkerInit struct {
	ServerId msg.String
	SeqNum   msg.Uint64
	Markers  []InteractiveMarker
}
