// Autogenerated with msg-import, do not edit.
package visualization_msgs

import (
	"github.com/aler9/goroslib/msg"
	"github.com/aler9/goroslib/msgs/geometry_msgs"
)

type InteractiveMarkerControl struct {
	Name                         msg.String
	Orientation                  geometry_msgs.Quaternion
	OrientationMode              msg.Uint8
	InteractionMode              msg.Uint8
	AlwaysVisible                msg.Bool
	Markers                      []Marker
	IndependentMarkerOrientation msg.Bool
	Description                  msg.String
}
