// Autogenerated with msg-import, do not edit.
package visualization_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/geometry_msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type Marker struct {
	Header                   std_msgs.Header
	Ns                       msgs.String
	Id                       msgs.Int32
	Type                     msgs.Int32
	Action                   msgs.Int32
	Pose                     geometry_msgs.Pose
	Scale                    geometry_msgs.Vector3
	Color                    std_msgs.ColorRGBA
	Lifetime                 msgs.Duration
	FrameLocked              msgs.Bool
	Points                   []geometry_msgs.Point
	Colors                   []std_msgs.ColorRGBA
	Text                     msgs.String
	MeshResource             msgs.String
	MeshUseEmbeddedMaterials msgs.Bool
}
