// Autogenerated with msg-import, do not edit.
package visualization_msgs

import (
	"github.com/aler9/goroslib/msg"
)

type MenuEntry struct {
	Id          msg.Uint32
	ParentId    msg.Uint32
	Title       msg.String
	Command     msg.String
	CommandType msg.Uint8
}
