// Autogenerated with msg-import, do not edit.
package visualization_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type MenuEntry struct {
	Id          msgs.Uint32
	ParentId    msgs.Uint32
	Title       msgs.String
	Command     msgs.String
	CommandType msgs.Uint8
}
