//autogenerated:yes
//nolint:revive,lll
package geographic_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/uuid_msgs"
)

type GetRoutePlanReq struct {
	msg.Package `ros:"geographic_msgs"`
	Network     uuid_msgs.UniqueID
	Start       uuid_msgs.UniqueID
	Goal        uuid_msgs.UniqueID
}

type GetRoutePlanRes struct {
	msg.Package `ros:"geographic_msgs"`
	Success     bool
	Status      string
	Plan        RoutePath
}

type GetRoutePlan struct {
	msg.Package `ros:"geographic_msgs"`
	GetRoutePlanReq
	GetRoutePlanRes
}
