//autogenerated:yes
//nolint:revive,lll
package geographic_msgs

import (
	"github.com/aler9/goroslib/pkg/msg"
)

type GetGeographicMapReq struct {
	msg.Package `ros:"geographic_msgs"`
	Url         string
	Bounds      BoundingBox
}

type GetGeographicMapRes struct {
	msg.Package `ros:"geographic_msgs"`
	Success     bool
	Status      string
	Map         GeographicMap
}

type GetGeographicMap struct {
	msg.Package `ros:"geographic_msgs"`
	GetGeographicMapReq
	GetGeographicMapRes
}
