// Autogenerated with msg-import, do not edit.
package geometry_msgs

import (
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type AccelWithCovarianceStamped struct {
	Header std_msgs.Header
	Accel  AccelWithCovariance
}
