// Autogenerated with msg-import, do not edit.
package geometry_msgs

import (
	"github.com/aler9/goroslib/msg"
)

type Inertia struct {
	M   msg.Float64
	Com Vector3
	Ixx msg.Float64
	Ixy msg.Float64
	Ixz msg.Float64
	Iyy msg.Float64
	Iyz msg.Float64
	Izz msg.Float64
}
