// Autogenerated with msg-import, do not edit.
package geometry_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type TransformStamped struct {
	Header       std_msgs.Header
	ChildFrameId msgs.String
	Transform    Transform
}
