// Autogenerated with msg-import, do not edit.
package geometry_msgs

import (
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type TwistWithCovarianceStamped struct {
	Header std_msgs.Header
	Twist  TwistWithCovariance
}
