// Autogenerated with msg-import, do not edit.
package geometry_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type Vector3 struct {
	msgs.Package `ros:"geometry_msgs"`
	X            float64
	Y            float64
	Z            float64
}
