// Autogenerated with msg-import, do not edit.
package geometry_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type Vector3 struct {
	msgs.Package `ros:"geometry_msgs"`
	X            msgs.Float64
	Y            msgs.Float64
	Z            msgs.Float64
}
