//autogenerated:yes
//nolint:revive,lll
package vision_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/std_msgs"
)

type BoundingBox2DArray struct {
	msg.Package `ros:"vision_msgs"`
	Header      std_msgs.Header
	Boxes       []BoundingBox2D
}
