//autogenerated:yes
//nolint:revive,lll
package geometry_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type TwistWithCovariance struct {
	msg.Package `ros:"geometry_msgs"`
	Twist       Twist
	Covariance  [36]float64
}
