//autogenerated:yes
//nolint:revive,lll
package geometry_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type Transform struct {
	msg.Package `ros:"geometry_msgs"`
	Translation Vector3
	Rotation    Quaternion
}
