//autogenerated:yes
//nolint:revive,lll
package geometry_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type Polygon struct {
	msg.Package `ros:"geometry_msgs"`
	Points      []Point32
}
