//autogenerated:yes
//nolint:revive,lll
package geometry_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type Wrench struct {
	msg.Package `ros:"geometry_msgs"`
	Force       Vector3
	Torque      Vector3
}
