//autogenerated:yes
//nolint:revive,lll
package shape_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/geometry_msgs"
)

type Mesh struct {
	msg.Package `ros:"shape_msgs"`
	Triangles   []MeshTriangle
	Vertices    []geometry_msgs.Point
}
