//autogenerated:yes
//nolint:revive,lll
package std_srvs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type SetBoolReq struct {
	msg.Package `ros:"std_srvs"`
	Data        bool
}

type SetBoolRes struct {
	msg.Package `ros:"std_srvs"`
	Success     bool
	Message     string
}

type SetBool struct {
	msg.Package `ros:"std_srvs"`
	SetBoolReq
	SetBoolRes
}
