//autogenerated:yes
//nolint:revive,lll
package velodyne_msgs

import (
	"time"

	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type VelodynePacket struct {
	msg.Package `ros:"velodyne_msgs"`
	Stamp       time.Time
	Data        [1206]uint8
}
