// Autogenerated with msg-import, do not edit.
package std_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type ColorRGBA struct {
	msgs.Package `ros:"std_msgs"`
	R            msgs.Float32
	G            msgs.Float32
	B            msgs.Float32
	A            msgs.Float32
}
