// Autogenerated with msg-import, do not edit.
package std_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type Header struct {
	msgs.Package `ros:"std_msgs"`
	Seq          msgs.Uint32
	Stamp        msgs.Time
	FrameId      msgs.String
}
