// Autogenerated with msg-import, do not edit.
package std_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type MultiArrayLayout struct {
	Dim        []MultiArrayDimension
	DataOffset msgs.Uint32
}
