// Autogenerated with msg-import, do not edit.
package std_msgs

import (
	"github.com/aler9/goroslib/msg"
)

type MultiArrayLayout struct {
	Dim        []MultiArrayDimension
	DataOffset msg.Uint32
}
