// Autogenerated with msg-import, do not edit.
package std_msgs

import (
	"github.com/aler9/goroslib/msg"
)

type MultiArrayDimension struct {
	Label  msg.String
	Size   msg.Uint32
	Stride msg.Uint32
}
