// Autogenerated with msg-import, do not edit.
package std_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type MultiArrayDimension struct {
	Label  msgs.String
	Size   msgs.Uint32
	Stride msgs.Uint32
}
