// Package std_msgs contains message definitions (autogenerated).
package std_msgs

import (
	"github.com/aler9/goroslib/msg"
	"time"
)

type Bool struct {
	msg.Package `ros:"std_msgs"`
	Data        bool
}

type Byte struct {
	msg.Package `ros:"std_msgs"`
	Data        int8 `ros:"byte"`
}

type ByteMultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []int8 `ros:"byte"`
}

type Char struct {
	msg.Package `ros:"std_msgs"`
	Data        uint8 `ros:"char"`
}

type ColorRGBA struct {
	msg.Package `ros:"std_msgs"`
	R           float32
	G           float32
	B           float32
	A           float32
}

type Duration struct {
	msg.Package `ros:"std_msgs"`
	Data        time.Duration
}

type Empty struct {
	msg.Package `ros:"std_msgs"`
}

type Float32 struct {
	msg.Package `ros:"std_msgs"`
	Data        float32
}

type Float32MultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []float32
}

type Float64 struct {
	msg.Package `ros:"std_msgs"`
	Data        float64
}

type Float64MultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []float64
}

type Header struct {
	msg.Package `ros:"std_msgs"`
	Seq         uint32
	Stamp       time.Time
	FrameId     string
}

type Int16 struct {
	msg.Package `ros:"std_msgs"`
	Data        int16
}

type Int16MultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []int16
}

type Int32 struct {
	msg.Package `ros:"std_msgs"`
	Data        int32
}

type Int32MultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []int32
}

type Int64 struct {
	msg.Package `ros:"std_msgs"`
	Data        int64
}

type Int64MultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []int64
}

type Int8 struct {
	msg.Package `ros:"std_msgs"`
	Data        int8
}

type Int8MultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []int8
}

type MultiArrayDimension struct {
	msg.Package `ros:"std_msgs"`
	Label       string
	Size        uint32
	Stride      uint32
}

type MultiArrayLayout struct {
	msg.Package `ros:"std_msgs"`
	Dim         []MultiArrayDimension
	DataOffset  uint32
}

type String struct {
	msg.Package `ros:"std_msgs"`
	Data        string
}

type Time struct {
	msg.Package `ros:"std_msgs"`
	Data        time.Time
}

type UInt16 struct {
	msg.Package `ros:"std_msgs"`
	Data        uint16
}

type UInt16MultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []uint16
}

type UInt32 struct {
	msg.Package `ros:"std_msgs"`
	Data        uint32
}

type UInt32MultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []uint32
}

type UInt64 struct {
	msg.Package `ros:"std_msgs"`
	Data        uint64
}

type UInt64MultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []uint64
}

type UInt8 struct {
	msg.Package `ros:"std_msgs"`
	Data        uint8
}

type UInt8MultiArray struct {
	msg.Package `ros:"std_msgs"`
	Layout      MultiArrayLayout
	Data        []uint8
}
