//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/trajectory_msgs"
)

type JointTrajectoryActionGoal struct {
	msg.Package `ros:"control_msgs"`
	Trajectory  trajectory_msgs.JointTrajectory
}

type JointTrajectoryActionResult struct {
	msg.Package `ros:"control_msgs"`
}

type JointTrajectoryActionFeedback struct {
	msg.Package `ros:"control_msgs"`
}

type JointTrajectoryAction struct {
	msg.Package `ros:"control_msgs"`
	JointTrajectoryActionGoal
	JointTrajectoryActionResult
	JointTrajectoryActionFeedback
}
