//autogenerated:yes
//nolint:revive,lll
package control_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type GripperCommand struct {
	msg.Package `ros:"control_msgs"`
	Position    float64
	MaxEffort   float64
}
