//autogenerated:yes
//nolint:revive,lll
package sensor_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type ChannelFloat32 struct {
	msg.Package `ros:"sensor_msgs"`
	Name        string
	Values      []float32
}
