package cmd

import (
	"fmt"
	"io"
	"strings"
	"text/template"

	"github.com/bluenviron/goroslib/v2/pkg/msgconv"
)

var tplSrv = template.Must(template.New("").Parse(
	`//autogenerated:yes
//nolint:revive,lll
package {{ .GoPkgName }}

import (
{{- range $k, $v := .Imports }}
    "{{ $k }}"
{{- end }}
)
{{ .Request }}
{{ .Response }}
type {{ .Name }} struct {
{{- if .RosPkgName }}
    msg.Package ` + "`" + `ros:"{{ .RosPkgName }}"` + "`" + `
{{- end }}
    {{ .Name }}Req
    {{ .Name }}Res
}
`))

// ImportSrv generates Go file from a .srv file and writes to the io.Writer.
func ImportSrv(u string, goPkgName string, rosPkgName string, w io.Writer) error {
	name := getName(u, ".srv")
	content, err := getContent(u)
	if err != nil {
		return err
	}

	parts := strings.Split(content, "---")
	if len(parts) != 2 {
		return fmt.Errorf("definition must contain a request and a response")
	}

	reqDef, err := msgconv.ParseMessageDefinition(goPkgName, goPkgName, name+"Req", parts[0])
	if err != nil {
		return err
	}

	resDef, err := msgconv.ParseMessageDefinition(goPkgName, goPkgName, name+"Res", parts[1])
	if err != nil {
		return err
	}

	imports := make(map[string]struct{})
	for i := range reqDef.Imports {
		imports[i] = struct{}{}
	}
	for i := range resDef.Imports {
		imports[i] = struct{}{}
	}

	request, err := reqDef.Write()
	if err != nil {
		return err
	}

	response, err := resDef.Write()
	if err != nil {
		return err
	}

	return tplSrv.Execute(w, map[string]interface{}{
		"GoPkgName":  goPkgName,
		"RosPkgName": rosPkgName,
		"Imports":    imports,
		"Request":    request,
		"Response":   response,
		"Name":       name,
	})
}
