//autogenerated:yes
//nolint:revive,lll
package visualization_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type MarkerArray struct {
	msg.Package `ros:"visualization_msgs"`
	Markers     []Marker
}
