// Autogenerated with msg-import, do not edit.
package nav_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/geometry_msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type GridCells struct {
	Header     std_msgs.Header
	CellWidth  msgs.Float32
	CellHeight msgs.Float32
	Cells      []geometry_msgs.Point
}
