// Autogenerated with msg-import, do not edit.
package nav_msgs

import (
	"github.com/aler9/goroslib/msg"
	"github.com/aler9/goroslib/msgs/geometry_msgs"
)

type MapMetaData struct {
	MapLoadTime msg.Time
	Resolution  msg.Float32
	Width       msg.Uint32
	Height      msg.Uint32
	Origin      geometry_msgs.Pose
}
