//autogenerated:yes
//nolint:revive,lll
package audio_common_msgs

import (
	"github.com/aler9/goroslib/pkg/msg"
	"github.com/aler9/goroslib/pkg/msgs/std_msgs"
)

type AudioDataStamped struct {
	msg.Package `ros:"audio_common_msgs"`
	Header      std_msgs.Header
	Audio       AudioData
}
