// Autogenerated with msg-import, do not edit.
package rosgraph_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"time"
)

type Clock struct {
	msgs.Package `ros:"rosgraph_msgs"`
	Clock        time.Time
}
