// Package rosgraph_msgs contains message definitions (autogenerated).
package rosgraph_msgs

import (
	"github.com/aler9/goroslib/msg"
	"github.com/aler9/goroslib/msgs/std_msgs"
	"time"
)

const (
	DEBUG int8 = 1
	INFO  int8 = 2
	WARN  int8 = 4
	ERROR int8 = 8
	FATAL int8 = 16
)

type Clock struct {
	msg.Package `ros:"rosgraph_msgs"`
	Clock       time.Time
}

type Log struct {
	msg.Package     `ros:"rosgraph_msgs"`
	msg.Definitions `ros:"int8 DEBUG=1,int8 INFO=2,int8 WARN=4,int8 ERROR=8,int8 FATAL=16"`
	Header          std_msgs.Header
	Level           int8 `ros:"byte"`
	Name            string
	Msg             string
	File            string
	Function        string
	Line            uint32
	Topics          []string
}

type TopicStatistics struct {
	msg.Package    `ros:"rosgraph_msgs"`
	Topic          string
	NodePub        string
	NodeSub        string
	WindowStart    time.Time
	WindowStop     time.Time
	DeliveredMsgs  int32
	DroppedMsgs    int32
	Traffic        int32
	PeriodMean     time.Duration
	PeriodStddev   time.Duration
	PeriodMax      time.Duration
	StampAgeMean   time.Duration
	StampAgeStddev time.Duration
	StampAgeMax    time.Duration
}
