//autogenerated:yes
//nolint:revive,lll
package diagnostic_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type KeyValue struct {
	msg.Package `ros:"diagnostic_msgs"`
	Key         string
	Value       string
}
