//autogenerated:yes
//nolint:revive,lll
package diagnostic_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
)

type SelfTestReq struct {
	msg.Package `ros:"diagnostic_msgs"`
}

type SelfTestRes struct {
	msg.Package `ros:"diagnostic_msgs"`
	Id          string
	Passed      int8 `rostype:"byte"`
	Status      []DiagnosticStatus
}

type SelfTest struct {
	msg.Package `ros:"diagnostic_msgs"`
	SelfTestReq
	SelfTestRes
}
