// Autogenerated with msg-import, do not edit.
package shape_msgs

import (
	"github.com/aler9/goroslib/msgs/geometry_msgs"
)

type Mesh struct {
	Triangles []MeshTriangle
	Vertices  []geometry_msgs.Point
}
