// Package shape_msgs contains message definitions (autogenerated).
package shape_msgs

import (
	"github.com/aler9/goroslib/msg"
	"github.com/aler9/goroslib/msgs/geometry_msgs"
)

const (
	BOX             uint8 = 1
	SPHERE          uint8 = 2
	CYLINDER        uint8 = 3
	CONE            uint8 = 4
	BOX_X           uint8 = 0
	BOX_Y           uint8 = 1
	BOX_Z           uint8 = 2
	SPHERE_RADIUS   uint8 = 0
	CYLINDER_HEIGHT uint8 = 0
	CYLINDER_RADIUS uint8 = 1
	CONE_HEIGHT     uint8 = 0
	CONE_RADIUS     uint8 = 1
)

type Mesh struct {
	msg.Package `ros:"shape_msgs"`
	Triangles   []MeshTriangle
	Vertices    []geometry_msgs.Point
}

type MeshTriangle struct {
	msg.Package   `ros:"shape_msgs"`
	VertexIndices [3]uint32
}

type Plane struct {
	msg.Package `ros:"shape_msgs"`
	Coef        [4]float64
}

type SolidPrimitive struct {
	msg.Package     `ros:"shape_msgs"`
	msg.Definitions `ros:"uint8 BOX=1,uint8 SPHERE=2,uint8 CYLINDER=3,uint8 CONE=4,uint8 BOX_X=0,uint8 BOX_Y=1,uint8 BOX_Z=2,uint8 SPHERE_RADIUS=0,uint8 CYLINDER_HEIGHT=0,uint8 CYLINDER_RADIUS=1,uint8 CONE_HEIGHT=0,uint8 CONE_RADIUS=1"`
	Type            uint8
	Dimensions      []float64
}
