// Autogenerated with msg-import, do not edit.
package shape_msgs

import (
	"github.com/aler9/goroslib/msgs"
)

type SolidPrimitive struct {
	msgs.Package `ros:"shape_msgs"`
	Type         msgs.Uint8
	Dimensions   []msgs.Float64
}
