// Autogenerated with msg-import, do not edit.
package stereo_msgs

import (
	"github.com/aler9/goroslib/msgs"
	"github.com/aler9/goroslib/msgs/sensor_msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type DisparityImage struct {
	msgs.Package `ros:"stereo_msgs"`
	Header       std_msgs.Header
	Image        sensor_msgs.Image
	F            msgs.Float32
	T            msgs.Float32
	ValidWindow  sensor_msgs.RegionOfInterest
	MinDisparity msgs.Float32
	MaxDisparity msgs.Float32
	DeltaD       msgs.Float32
}
