// Autogenerated with msg-import, do not edit.
package stereo_msgs

import (
	"github.com/aler9/goroslib/msg"
	"github.com/aler9/goroslib/msgs/sensor_msgs"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type DisparityImage struct {
	Header       std_msgs.Header
	Image        sensor_msgs.Image
	F            msg.Float32
	T            msg.Float32
	ValidWindow  sensor_msgs.RegionOfInterest
	MinDisparity msg.Float32
	MaxDisparity msg.Float32
	DeltaD       msg.Float32
}
