//autogenerated:yes
//nolint:revive,lll
package tf2_msgs

import (
	"github.com/bluenviron/goroslib/v2/pkg/msg"
	"github.com/bluenviron/goroslib/v2/pkg/msgs/geometry_msgs"
)

type TFMessage struct {
	msg.Package `ros:"tf2_msgs"`
	Transforms  []geometry_msgs.TransformStamped
}
