// Autogenerated with msg-import, do not edit.
package diagnostic_msgs

import (
	"github.com/aler9/goroslib/msgs/std_msgs"
)

type DiagnosticArray struct {
	Header std_msgs.Header
	Status []DiagnosticStatus
}
