// Autogenerated with msg-import, do not edit.
package diagnostic_msgs

import (
	"github.com/aler9/goroslib/msg"
)

type DiagnosticStatus struct {
	Level      msg.Byte
	Name       msg.String
	Message    msg.String
	HardwareId msg.String
	Values     []KeyValue
}
