// Package diagnostic_msgs contains message definitions (autogenerated).
package diagnostic_msgs

import (
	"github.com/aler9/goroslib/msg"
	"github.com/aler9/goroslib/msgs/std_msgs"
)

const (
	OK    int8 = 0
	WARN  int8 = 1
	ERROR int8 = 2
	STALE int8 = 3
)

type DiagnosticArray struct {
	msg.Package `ros:"diagnostic_msgs"`
	Header      std_msgs.Header
	Status      []DiagnosticStatus
}

type DiagnosticStatus struct {
	msg.Package     `ros:"diagnostic_msgs"`
	msg.Definitions `ros:"int8 OK=0,int8 WARN=1,int8 ERROR=2,int8 STALE=3"`
	Level           int8 `ros:"byte"`
	Name            string
	Message         string
	HardwareId      string
	Values          []KeyValue
}

type KeyValue struct {
	msg.Package `ros:"diagnostic_msgs"`
	Key         string
	Value       string
}
